project:
  type: website
  output-dir: docs

website:
  open-graph: true
  site-url: https://annieradams.github.io/
  favicon: images/AA-logo-white.png
  navbar:
    title: false
    logo: images/AA-logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd
      - posts.qmd
    right:
      - icon: github
        href: https://github.com/annieradams
    page-footer:
    center: "Copyright 2023, Annie Adams"
    background: secondary

format:
  html:
    theme: styles.scss
    #css: styles.css
    toc: true
    page-layout: full

editor: visual

