---
title: "About"
subtitle: "A bit more about me and what I have been up to!"
---

### The Education {{< fa book >}}

After getting my Associate's Degree in Mathematics from community college, I discovered the field of data science at UCSB. I quickly grew to love the field and was ever enamored by the insight our data is capable of telling us. Along the way, I also learned a lot about the ethics of data science and the importance of unbiased data at the point of collection. I took both of these pieces with me as a fellow for the Central Coast Data Science Fellowship (CCDSP). I sat on the outreach committee, where I got to share my newfound love of data science with high school students who were not privy to this powerful field. In my final year of my undergrad, I worked with the Energy and Environment Transitions lab on campus (ENVENT) for my capstone project. A team of three undergrads and myself were tasked with analyzing how demographic variables are differentially predictive of climate change opinions, using global survey data. It was during this project that I discovered the specific sector of data science I want to work within - Environmental Data Science! I returned to school in the fall of 2023 and received my Master's in Environmental Data Science! Despite both being environmental, my capstone project during my master's program was so different than my capstone during my undergrad! I was lucky to work with Darn Tough, a Vermont-based sock manufacturer, to help them streamline their carbon emission calculation process, as well as provide them with tangible suggestions on how to reach their reduction targets.

### The internship {{< fa fish >}}

Immediately after graduating from the University of California, Santa Barbara, with a Bachelor of Science in Statistics and Data Science and a minor in Feminist Studies, I took on an internship with California Cooperative Oceanic Fisheries Investigations (CalCOFI). My role in this internship was to create an interactive data storytelling tool that would inform California Coastal residents about the threat of hypoxia in our California Coastal Ecosystem. The project stemmed from the realization that California Coastal residents are not widely informed about what hypoxia is and how it changes with climate change. The project heavily relied on science communication to create an interactive web-based primer through "scrolly-telling." Upon finishing the primer, another intern and I started an outreach portion of the internship where we went to local high schools to inform students about the field of environmental data science. We created an activity to help the students get their hands dirty analyzing real-life environmental data collected by CalCOFI!

### The life outside of my computer! {{< fa mountain-sun >}}

I love to code, analyze, make cool visualizations, and learn about subjects I know little about through data science/analysis. But this isn't all I do! I am a Southern California native and I take full advantage of it! I grew up mountain biking and hiking and have taken part in those activities ever since! I recently cheated on my mountain bike by purchasing a gravel bike and have since become hooked on road cycling and bikepacking. I have lived in Ventura County my whole life but moved to Ventura proper in 2022 and haven't stopped biking my way between here and Santa Barbara since - the views never get old!

Over the past year, I have picked up an interest in zero-waste cooking/cooking in general. I try and make a new semi-elaborate recipe every week. I make all my own almond and oat mylk, and repurpose the almond/oat pulp to make meal, crackers, and granola (one day I want to make my coffee cart and sell matcha lattes using my homemade nut milks as a passion project!)! Living in an apartment without a garden, I don't have a way to effectively compost. Instead, I freeze all my vegetable scraps and make vegetable broth each week with them. I am planning to start dabbling in bread-making soon!
